const fs=require('fs'),path=require('path'),os=require('os'),assert=require('assert/strict'),{spawn}=require('child_process'),ExcelJS=require('exceljs');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'pm122-'));const port=Number(process.env.TEST_PORT||13050);let child,token;const logs=[];
fs.cpSync(path.join(__dirname,'data','config'),path.join(root,'config'),{recursive:true});
fs.writeFileSync(path.join(root,'config','email.json'),JSON.stringify({accounts:[]}));
const year=new Date().getFullYear(),month=new Date().getMonth()+1;
const base=`http://127.0.0.1:${port}`;
async function api(url,method='GET',body){const r=await fetch(base+url,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw Error(method+' '+url+' '+r.status+' '+JSON.stringify(j));return j;}
const ar=()=>api(`/api/task-management?line=test&year=${year}`);const mr=()=>api(`/api/monthly-task-management?line=test&year=${year}&month=${month}`);
const rebuild=()=>api(`/api/pm-master/lines/test/rebuild-monthly/${year}/${month}`,'POST',{});
async function book(kind){const file=kind==='annual'?path.join(root,'annual',`test PM ${year}.xlsx`):path.join(root,'monthly_work','test',`test PM_${year}_${String(month).padStart(2,'0')}.xlsx`);const wb=new ExcelJS.Workbook();await wb.xlsx.readFile(file);return wb.worksheets[0];}
async function verify(n,machines=['C1','C2']){for(const kind of ['annual','monthly']){const ws=await book(kind),tasks=[];const seen=new Set();for(let r=7;r<=ws.rowCount;r++){const activity=ws.getCell(r,8).value;if(!['planed','machine'].includes(activity))continue;const no=ws.getCell(r,2).value;seen.add(no);assert(machines.includes(no),kind+' invalid machine '+no);assert.equal(ws.getCell(r,1).value,'Mixing');assert.equal(ws.getCell(r,3).value,'Mixer '+no);assert.equal(ws.getCell(r,4).value,'ID '+no);assert.equal(ws.getCell(r,5).value,'TFT');if(activity==='planed'){tasks.push(ws.getCell(r,kind==='annual'?69:51).value);assert.equal(ws.getCell(r+1,8).value,'done');}}assert.equal(tasks.length,n,kind+' task count');assert.deepEqual([...seen].sort(),machines.slice().sort());assert.equal(new Set(tasks).size,n);if(kind==='annual'){assert.equal(ws.getCell('A3').value,machines.length);assert.equal(ws.getCell('B3').value,n);}}}
async function start(){child=spawn(process.execPath,['server.js'],{cwd:__dirname,env:{...process.env,PORT:String(port),PM_DATA_ROOT:root,PM_TEST_MODE:'1'},stdio:['ignore','pipe','pipe']});child.stdout.on('data',d=>logs.push(d.toString()));child.stderr.on('data',d=>logs.push(d.toString()));for(let i=0;i<100;i++){try{const j=await api('/api/login','POST',{username:'admin',password:'1234'});token=j.token;return;}catch{}await new Promise(r=>setTimeout(r,100));}throw Error('Server failed '+logs.join(''));}
(async()=>{try{await start();await api('/api/pm-master/lines','POST',{name:'test',year});for(const no of ['C1','C2']){await api('/api/pm-master/lines/test/machines','POST',{year,machineNo:no,machineName:'Mixer '+no,section:'Mixing',machineIdentified:'ID '+no,type:'TFT'});const ws=await book('annual');assert.equal(ws.getCell('A3').value,no==='C1'?1:2);}
for(const no of ['C1','C2'])for(let i=1;i<=2;i++)await api(`/api/task-management/test/${year}`,'POST',{machineNo:no,maintenance:'Task '+i,part:'Part '+i,code:1,firstPmDate:`${year}-01-02`,calculationMethod:'calendar',calendarFrequency:'weekly'});
await rebuild();await verify(4);console.log('PASS fresh Line / C1 / C2 / four tasks / Annual + Monthly identity and KPI');
if(process.env.PM_UI_FIXTURE){console.log('UI FIXTURE '+root);await new Promise(()=>{});}
let tasks=(await mr()).tasks;const retained=tasks.find(t=>t.machineNo==='C2');await api(`/api/task/test/${retained.row}/done`,'POST',{});let ws=await book('monthly');let doneCol;for(let c=16;c<=20;c++)if(ws.getCell(retained.row+1,c).value===6)doneCol=c;assert(doneCol,'Done was not stored');const doneUser=ws.getCell(retained.row,doneCol+5).value,doneDate=ws.getCell(retained.row+1,doneCol+5).value.toISOString();
let removed=tasks.find(t=>t.machineNo==='C1');await api(`/api/task-management-both/test/${year}/${month}/${removed.row}`,'DELETE',{taskId:removed.taskId});await verify(3);tasks=(await mr()).tasks;let kept=tasks.find(t=>t.taskId===retained.taskId);ws=await book('monthly');assert.equal(ws.getCell(kept.row+1,doneCol).value,6);assert.equal(ws.getCell(kept.row,doneCol+5).value,doneUser);assert.equal(ws.getCell(kept.row+1,doneCol+5).value.toISOString(),doneDate);console.log('PASS delete C1 task preserves other tasks, merges and Done/User/Date');
removed=tasks.find(t=>t.machineNo==='C1');await api(`/api/task-management-both/test/${year}/${month}/${removed.row}`,'DELETE',{taskId:removed.taskId});await verify(2);console.log('PASS last C1 task deleted, machine remains');
// Stable IDs distinguish duplicate descriptions; month-only overrides survive regeneration.
await api(`/api/monthly-task-management/test/${year}/${month}`,'POST',{machineNo:'C1',maintenance:'Local',part:'Local',code:2,weekIndexes:[1]});await rebuild();let local=(await mr()).tasks.find(t=>t.maintenance==='Local');assert(local);assert.equal((await ar()).tasks.length,2);await api(`/api/monthly-task-management/test/${year}/${month}/${local.row}`,'PUT',{taskId:local.taskId,machineNo:'C1',maintenance:'Local edit',code:3,weekIndexes:[2]});await rebuild();local=(await mr()).tasks.find(t=>t.taskId===local.taskId);assert.equal(local.maintenance,'Local edit');assert.deepEqual(local.weekIndexes,[2]);await api(`/api/monthly-task-management/test/${year}/${month}/${local.row}`,'DELETE',{taskId:local.taskId});await rebuild();assert.equal((await mr()).tasks.length,2);console.log('PASS month-only Add/Edit/Delete persists across rebuild');
kept=(await mr()).tasks.find(t=>t.taskId===retained.taskId);await api(`/api/task/test/${kept.row}/undo`,'POST',{});await rebuild();kept=(await mr()).tasks.find(t=>t.taskId===retained.taskId);ws=await book('monthly');assert.equal(ws.getCell(kept.row+1,doneCol).value,0);console.log('PASS Undo persisted across rebuild');
// A report can be deleted and regenerated entirely from JSON state.
await api('/api/task/test/'+kept.row+'/done','POST',{taskId:kept.taskId});
const report=path.join(root,'monthly_work','test',`test PM_${year}_${String(month).padStart(2,'0')}.xlsx`);fs.renameSync(report,report+'.removed-for-test');await rebuild();ws=await book('monthly');assert.equal(ws.getCell(kept.row+1,doneCol).value,6);assert.equal(ws.getCell(kept.row,doneCol+5).value,doneUser);console.log('PASS report removed: execution recovered from JSON without Excel source');


// Machine rename updates task ownership, then restores the original identity.
for(const no of ['C22','C2'])await api('/api/pm-master/lines/test/machines/'+(no==='C22'?'C2':'C22'),'PUT',{year,machineNo:no,machineName:'Mixer '+no,section:'Mixing',machineIdentified:'ID '+no,type:'TFT',applyCurrentMonthly:true,monthlyYear:year,monthlyMonth:month});
await verify(2);assert((await ar()).tasks.every(t=>t.machineNo==='C2'));console.log('PASS machine rename preserves task IDs and ownership');
let edit=(await ar()).tasks[0];const schedule=edit.scheduleWeeks;
await api('/api/task-management/test/'+year+'/'+edit.row,'PUT',{taskId:edit.taskId,machineNo:'C2',maintenance:'Edited',code:5,applyCodeToPlannedWeeks:false});
assert.deepEqual((await ar()).tasks[0].scheduleWeeks,schedule);assert.equal((await ar()).tasks[0].dominantCode,1);
await api('/api/task-management/test/'+year+'/'+edit.row+'/deactivate','POST',{taskId:edit.taskId});await api('/api/pm-master/lines/test/rebuild-annual/'+year,'POST',{});assert.equal((await ar()).tasks[0].isActive,false);await api('/api/task-management/test/'+year+'/'+edit.row+'/activate','POST',{taskId:edit.taskId});
let stale=false;try{await api('/api/task-management/test/'+year+'/'+edit.row,'DELETE',{taskId:'stale-id'});}catch(e){stale=e.message.includes('409');}assert(stale);console.log('PASS task metadata edit preserves recurrence; activation and stale ID guard');
await api('/api/pm-master/lines/test','PUT',{name:'test_renamed'});let renamed=await api('/api/task-management?line=test_renamed&year='+year);assert.equal(renamed.tasks.length,2);await api('/api/pm-master/lines/test_renamed','PUT',{name:'test'});await rebuild();await verify(2);console.log('PASS Line rename updates master task ownership');
await api('/api/pm-master/lines/test/machines/C1','DELETE',{mode:'annual',year,applyCurrentMonthly:true,monthlyYear:year,monthlyMonth:month});await verify(2,['C2']);await api('/api/pm-master/lines/test/machines','POST',{year,machineNo:'C1',machineName:'Mixer C1',section:'Mixing',machineIdentified:'ID C1',type:'TFT',applyCurrentMonthly:true,monthlyYear:year,monthlyMonth:month});await verify(2);console.log('PASS delete/re-add zero-task machine');
for(const t of (await ar()).tasks.slice().reverse())await api(`/api/task-management/test/${year}/${t.row}`,'DELETE',{taskId:t.taskId});await rebuild();await verify(0);await api(`/api/pm-master/lines/test/rebuild-annual/${year}`,'POST',{});assert.equal((await ar()).tasks.length,0);console.log('PASS delete final system task does not bootstrap ghost from Excel');
await api('/api/pm-master/lines/test','DELETE',{mode:'system'});await api('/api/pm-master/lines','POST',{name:'test',year});assert.equal((await ar()).tasks.length,0);assert.equal((await api('/api/pm-master')).lines.find(l=>l.name==='test').machines.length,0);await rebuild();assert.equal((await mr()).tasks.length,0);console.log('PASS delete/recreate Line with old Excel retained: zero ghost tasks');
assert(fs.readdirSync(path.join(root,'monthly_archive')).length>0);
// Restart must retain initialized empty scopes and not import archived tasks.
await new Promise(resolve=>{child.once('exit',resolve);child.kill();});await start();assert.equal((await ar()).tasks.length,0);await rebuild();assert.equal((await mr()).tasks.length,0);console.log('PASS restart retains empty master and archive isolation');
// Concurrent adds are serialized, and both tasks survive.
await api('/api/pm-master/lines/test/machines','POST',{year,machineNo:'C1',machineName:'Mixer C1'});await Promise.all([1,2].map(i=>api('/api/task-management/test/'+year,'POST',{machineNo:'C1',maintenance:'Duplicate',part:'Same',code:1,firstPmDate:year+'-01-02'})));let duplicates=(await ar()).tasks;assert.equal(duplicates.length,2);assert.notEqual(duplicates[0].taskId,duplicates[1].taskId);await rebuild();let d=(await mr()).tasks[0];await api('/api/task-management-both/test/'+year+'/'+month+'/'+d.row,'DELETE',{taskId:d.taskId});assert.equal((await ar()).tasks.length,1);assert.equal((await mr()).tasks.length,1);console.log('PASS concurrent adds and identical descriptions remain separate by ID');
const masterFile=path.join(root,'pm_tasks.json'),healthy=fs.readFileSync(masterFile);fs.writeFileSync(masterFile,'broken');let rejected=false;try{await ar();}catch(e){rejected=e.message.includes('500');}assert(rejected);fs.writeFileSync(masterFile,healthy);console.log('PASS corrupt JSON rejected without falling back to Excel');

// Upgrade a real packaged legacy workbook (133 task pairs).
const annualDir=path.join(__dirname,'data','annual');const legacyName=fs.readdirSync(annualDir).find(f=>f.toLowerCase()==='cookies pm 2026.xlsx');assert(legacyName,'Packaged Cookies 2026 workbook is missing');const legacy=path.join(annualDir,legacyName);const legacyBook=new ExcelJS.Workbook();await legacyBook.xlsx.readFile(legacy);const legacyWs=legacyBook.worksheets[0];let legacyCount=0;for(let r=7;r<=legacyWs.rowCount;r++)if(String(legacyWs.getCell(r,8).value||'').trim().toLowerCase()==='planed')legacyCount++;fs.copyFileSync(legacy,path.join(root,'annual','Cookies PM 2026.xlsx'));
const migrated=await api('/api/task-management?line=Cookies&year=2026');assert.equal(migrated.tasks.length,legacyCount);const ids=migrated.tasks.map(t=>t.taskId);assert.equal(new Set(ids).size,legacyCount);await api('/api/pm-master/lines/Cookies/rebuild-annual/2026','POST',{});assert.deepEqual((await api('/api/task-management?line=Cookies&year=2026')).tasks.map(t=>t.taskId),ids);console.log('PASS real legacy Cookies migration: '+legacyCount+' tasks and stable IDs across rebuild');
await api('/api/pm-master/lines','POST',{name:'copied',year:2026,annualSource:'copy_existing',annualTemplateLine:'Cookies'});const copied=(await api('/api/task-management?line=copied&year=2026')).tasks;assert.equal(copied.length,legacyCount);assert(!copied.some(t=>ids.includes(t.taskId)));console.log('PASS explicit copy imports tasks with independent stable IDs');

console.log('ALL TESTS PASSED; isolated data: '+root);
}catch(e){console.error(e.stack);console.error(logs.join(''));process.exitCode=1;}finally{child?.kill();}})();
